server:
  port: 8081
  servlet:
    context-path: /notification
  max-http-request-header-size: 8MB

spring:
  main:
    allow-bean-definition-overriding: true
  jackson:
    serialization:
      indent-output: true
      write-dates-as-timestamps: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: notification-verify-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.example.notification_service.event.NotificationEvent
feign:
  hystrix:
    enabled: true  # Bật Hystrix cho Feign
